workflows:
  default-workflow:
    name: Build iOS for TestFlight
    environment:
      xcode: latest
      node: latest
      cocoapods: default

    scripts:
      - name: Clean CocoaPods Cache
        script: |
          cd ios
          rm -rf Pods/
          rm -rf Podfile.lock
          pod cache clean --all
          cd ..

      - name: Install Dependencies
        script: |
          npm install
          cd ios
          pod install --repo-update
          cd ..

      - name: Verify Workspace
        script: |
          if [ ! -f "ios/SubliminalAudioApp.xcworkspace" ]; then
            echo "Error: .xcworkspace file not found!"
            exit 1
          fi

      - name: Build iOS
        script: |
          xcodebuild -workspace ios/SubliminalAudioApp.xcworkspace \
          -scheme SubliminalAudioApp \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $CM_BUILD_DIR/SubliminalAudioApp.xcarchive archive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
          -archivePath $CM_BUILD_DIR/SubliminalAudioApp.xcarchive \
          -exportOptionsPlist ios/exportOptions.plist \
          -exportPath $CM_BUILD_DIR

    artifacts:
      - $CM_BUILD_DIR/*.ipa
