- name: Install JS Dependencies
  script: |
    npm install

- name: Remove internal RN boost spec
  script: |
    sed -i '' '/boost.podspec/d' node_modules/react-native/third-party-podspecs/boost.podspec

- name: Clean Pods & Cache
  script: |
    cd ios
    rm -rf Pods/ Podfile.lock
    pod cache clean --all
    cd ..

- name: Install CocoaPods
  script: |
    cd ios
    pod install --repo-update
    cd ..
