platform :ios, '14.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'SubliminalAudioApp' do
  config = use_native_modules!

  use_react_native!(
    path: config[:reactNativePath]
  )

  # Only install your local boost
  pod 'boost', path: './boost-local'

  post_install do |installer|
    react_native_post_install(installer)
    # Apple Silicon simulator tweak
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
